services:
  mysql:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: demo
    ports:
      - 3306:3306
    volumes:
      - ./docker-entrypoint-initdb.d/:/docker-entry-point-initdb.d/
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
