server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    server-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka
