server:
  port: 8088
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
spring:
  cloud:
    gateway:
      routes:
        - id: Microservice1
          uri: lb://USER
          Predicates:
            - Path=/users/**
        - id: Microservice2
          uri: lb://ORDER
          Predicates:
            - Path=/orders/**
        - id: Microservice3
          uri: http://PRODUCT
          Predicates:
            - Path=/products/**
        - id: Microservice4
          uri: lb://FEEDBACK
          Predicates:
            - Path=/feedbacks/**
        - id: Microservice5
          uri: lb://TEXT
          Predicates:
            - Path=/texts/**
        - id: Microservice6
          uri: lb://POINT
          Predicates:
            - Path=/points/**
        - id: Microservice7
          uri: lb://CERTIFICATE
          Predicates:
            - Path=/certificates/**
