server:
  port: 8087
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
spring:
  cloud:
    gateway:
      routes:
        - id: Microservice1
          uri: lb://USER
          Predicates:
            - Path=/users/**
        - id: Microservice2
          uri: lb://ORDER
          Predicates:
            - Path=/orders/**
        - id: Microservice3
          uri: http://PRODUCT
          Predicates:
            - Path=/products/**
        - id: Microservice4
          uri: lb://FEEDBACK
          Predicates:
            - Path=/feedbacks/**
